/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save an authenticated user note */
        post: operations["NotesController_saveNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NoteResponseDto: {
            content: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: date-time */
            updated_at: string;
        };
        SaveNoteDto: {
            content: string;
            /** Format: uuid */
            source_id: string;
            /** @enum {string} */
            source_type: "article" | "transcription";
        };
        SaveNoteResponseDto: {
            note: components["schemas"]["NoteResponseDto"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    NotesController_saveNote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveNoteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveNoteResponseDto"];
                };
            };
        };
    };
}
